---

language: python
python: "2.7"
sudo: required
services:
  - docker

install: pip install molecule docker-py
script:
  - export MOLECULE_APTPROXY_PATH="$PWD/00aptproxy" && touch "$MOLECULE_APTPROXY_PATH"
  - molecule --debug test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/