---
- name: Sync server-scripts
  git:
    repo=https://github.com/popstas/server-scripts.git
    dest=/usr/local/src/server-scripts
    version=v0.1
  tags: server-scripts

- name: Install server-scripts
  command:
    /usr/local/src/server-scripts/install.sh -y
    creates=/usr/share/server-scripts
  tags: server-scripts

- name: server-scripts config
  template: src=server-scripts.conf.j2 dest=/etc/server-scripts.conf owner=root mode=0644
  tags: server-scripts
