---

- name: Ensure cron and git installed (Debian)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - cron
    - git
  when: ansible_os_family == 'Debian'
  tags: [ server-scripts, install ]

- name: Ensure cron and git installed (RedHat)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - crontabs
    - git
  when: ansible_os_family == 'RedHat'
  tags: [ server-scripts, install ]

- name: Sync server-scripts
  git:
    repo: https://github.com/viasite/server-scripts.git
    version: "{{ server_scripts_version }}"
    dest: "{{ server_scripts_install_path }}"
    force: yes
  register: register_server_scripts_sync
  tags: [ server-scripts, install, upgrade ]

- name: Create executable links
  command: find "{{ server_scripts_install_path }}/bin" -type f -exec ln -s {} /usr/local/bin \;
  when: register_server_scripts_sync|changed
  tags: [ server-scripts, install, upgrade, skip_ansible_lint ]

- name: Create log directory
  file:
    path: "{{ server_scripts_logs_base_path }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  tags: [ server-scripts, install ]

- name: server-scripts config
  template:
    src: server-scripts.conf.j2
    dest: /etc/server-scripts.conf
    owner: root
    group: root
    mode: 0644
  tags: [ server-scripts, install, configure ]

- name: Configuring cron tasks
  cron:
    cron_file: "{{ item.cron_file | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    job: "{{ item.job | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    name: "{{ item.name | default(item) }}"
    special_time: "{{ item.special_time | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
  with_items: "{{ server_scripts_cron_tasks }}"
  tags: [ server-scripts, install, configure, cron ]
