---
- name: Sync server-scripts
  git:
    repo=https://github.com/popstas/server-scripts.git
    dest=/usr/local/src/server-scripts
    version={{ server_scripts_version }}
    force=yes
  register: server_scripts_sync
  tags: server-scripts

- name: Install server-scripts
  command:
    /usr/local/src/server-scripts/install.sh -y
  when: server_scripts_sync.changed
  tags: server-scripts

- name: server-scripts config
  template: src=server-scripts.conf.j2 dest=/etc/server-scripts.conf owner=root mode=0644
  tags: server-scripts
