---
driver:
  name: docker
platforms:
  - name: ansible-role-server-scripts-1604
    image: ubuntu:16.04

  - name: ansible-role-server-scripts-centos-7
    image: centos:7

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
